In [23]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import PCA

In [8]:
carE_df = pd.read_csv("carEvaluation.csv")
carE_df.head()

  buying  maint doors persons lug_boot safety values
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [9]:
carE_df.describe()

       buying  maint doors persons lug_boot safety values
count    1728   1728  1728    1728     1728   1728   1728
unique      4      4     4       3        3      3      4
top     vhigh  vhigh     2       2    small    low  unacc
freq      432    432   432     576      576    576   1210

In [16]:
carE_df.info()
carE_df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1728 non-null   str
 1   maint     1728 non-null   str
 2   doors     1728 non-null   str
 3   persons   1728 non-null   str
 4   lug_boot  1728 non-null   str
 5   safety    1728 non-null   str
 6   values    1728 non-null   str
dtypes: str(7)
memory usage: 94.6 KB

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
values      0
dtype: int64

Como pode-se perceber, nos dados do meu dataset escolhido não há dados faltosos, que poderiam influenciar nas minhas contas, sendo assim, a necessidade de uma limpeza prévia. Com o intuito de por em pratica a Atividade 1, modifiquei alguns itens da minha lista para implementar um método de limpeza (Apenas para teste, o utilizado no decorrer do trabalho é o original).

In [10]:
carE_teste_df = pd.read_csv("carEvaluation_limpeza.csv")
carE_teste_df.info()
carE_teste_df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1714 non-null   str
 1   maint     1714 non-null   str
 2   doors     1720 non-null   str
 3   persons   1720 non-null   str
 4   lug_boot  1714 non-null   str
 5   safety    1713 non-null   str
 6   values    1721 non-null   str
dtypes: str(7)
memory usage: 94.6 KB

buying      14
maint       14
doors        8
persons      8
lug_boot    14
safety      15
values       7
dtype: int64

Apaguei alguns valores, e usei o isnull() para identificar e o sum() para somar esse valores que eu removi, agora implementarei o método hot-deck que consiste em preencher com valor aleatorio de mesmo atributo de um objeto similar. Vou mostrar os 10 primeiros já que eu tirei alguns dados dele, e depois vou mostar por quais dados foram atribuidos.

In [11]:
carE_teste_df.head(10)

  buying  maint doors persons lug_boot safety values
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc
5  vhigh  vhigh     2       2      NaN    NaN  unacc
6  vhigh  vhigh     2       2      NaN    NaN  unacc
7  vhigh  vhigh     2       2      NaN    NaN  unacc
8  vhigh  vhigh     2       2      NaN    NaN  unacc
9  vhigh  vhigh     2       4      NaN    NaN  unacc

In [12]:
for col in carE_teste_df.columns:
    missing = carE_teste_df[col].isnull()
    carE_teste_df.loc[missing, col] = np.random.choice(carE_teste_df[col].dropna(), size=missing.sum())

In [13]:
carE_teste_df.head(10)

  buying  maint doors persons lug_boot safety values
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc
5  vhigh  vhigh     2       2    small   high  unacc
6  vhigh  vhigh     2       2      med   high  unacc
7  vhigh  vhigh     2       2      med    low  unacc
8  vhigh  vhigh     2       2      big   high  unacc
9  vhigh  vhigh     2       4      med    low  unacc

In [14]:
carE_teste_df.info()
carE_teste_df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1728 non-null   str
 1   maint     1728 non-null   str
 2   doors     1728 non-null   str
 3   persons   1728 non-null   str
 4   lug_boot  1728 non-null   str
 5   safety    1728 non-null   str
 6   values    1728 non-null   str
dtypes: str(7)
memory usage: 94.6 KB

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
values      0
dtype: int64

Com o teste agora temos nenhuma variável faltando, ou seja, todos os valores preenchidos.

Implementando os exercícios da Atividade 2: já que meu dataset é composto por dados categoricos, agora passarei para numérico para realizar a padronização e depois o PCA (já voltando com a tabela original).

In [22]:
le = LabelEncoder()

for col in carE_df.columns:
 carE_df[col] = le.fit_transform(carE_df[col])

print (carE_df.head())

   buying  maint  doors  persons  lug_boot  safety  values
0       3      3      0        0         2       1       2
1       3      3      0        0         2       2       2
2       3      3      0        0         2       0       2
3       3      3      0        0         1       1       2
4       3      3      0        0         1       2       2

Todos os dados foram passados para uma forma numérica utilizando o LabelEncoder, basicamente como se passasse e forma de opção, já que os valores dos atributos eram separados de tal forma:
   buying       v-high, high, med, low
   maint        v-high, high, med, low
   doors        2, 3, 4, 5-more
   persons      2, 4, more
   lug_boot     small, med, big
   safety       low, med, high

   class:
   values       unacc, acc, good, vgood

Já que meus dados são categóricos não faria muito sentido a implementação de padronização, já que a variação e a distancia dos dados não indicariam números reais, mas sim representativos. Mas para o exercício realizarei a implementação por meio do z-score e depois o PCA.

In [25]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(carE_df)

In [26]:
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
pca.explained_variance_ratio_

array([0.18722727, 0.14285714])